# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e2e7a49af4cdbc9cd9c3991fd5ac408c4990c43b92fbdc06125b32bdc503810bae3b292ea7c986772ce5a76fae993d8c931a7746bddded90db9203d0c0123c0
  tmdb_api_key: "b9b130879cbed0857587720aeb59bc98"

test:
  secret_key_base: 577c1676cf789798d1f1321a44b7c661f88f5b8449a9175f76a9436721cd1a20bdc3f87412d216a2c7be3895d0c6c69ef9b4373e19a146208382f0217f85361f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  tmdb_api_key: <%= ENV["TMDB_API_KEY"] %>
